backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
  repo: dannykennedy/quiz-nawarddeken

media_folder: "public/uploads" # Where media files will be stored
public_folder: "/uploads" # Where the media files can be accesed from the server
collections:
  - name: quizItems
    label: "Quiz Item"
    editor:
      preview: false
    folder: content/quizItems
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true # Allow users to create new documents in this collection
    summary: "{{fields.title}}"
    fields:
      - label: "English name"
        name: "title"
        widget: "string"
        required: true
        hint: "e.g. Cheeky Yam"
      - label: "Kundedjnjenghmi name"
        name: "labelKundedjnjenghmi"
        widget: "string"
        required: false
        hint: "e.g. Anyawok"
      - label: "Kunwinjku name"
        name: "labelKunwinjku"
        widget: "string"
        required: false
        hint: "e.g. Mankinjdjek"
      - label: "Scientific name"
        name: "labelScientific"
        widget: "string"
        required: false
        hint: "e.g. Dioscorea bulbifera"
      - label: "Image"
        name: "quizItemImage"
        widget: "image"
        required: false
        hint: "For best results, use a square image"
      - label: "Short description"
        name: "quizItemShortDescription"
        widget: "string"
        required: false
        hint: "e.g. Kundjewk runs from around January to mid-March"
      - label: "Audio Kunwinjku"
        name: "quizItemAudioKunwinjku"
        widget: "file"
        required: false
      - label: "Audio Kundedjnjenghmi"
        name: "quizItemAudioKundedjnjenghmi"
        widget: "file"
        required: false
      - label: "Audio English"
        name: "quizItemAudioEnglish"
        widget: "file"
        required: false
      - label: "Latitude"
        name: "latitude"
        widget: "string"
        required: false
        hint: "e.g. -12.460443"
      - label: "Longitude"
        name: "longitude"
        widget: "string"
        required: false
        hint: "e.g. 133.844517659562"
  - name: multipleChoiceQuestions
    label: "Multiple Choice Question"
    editor:
      preview: false
    folder: content/multipleChoiceQuestions
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Question Text"
        name: "title"
        widget: "string"
        required: false
      - widget: "select"
        label: "Question type"
        name: "questionType"
        options: ["Map", "Regular"]
      - widget: "object"
        label: "Image"
        name: "multipleChoiceQuestionImage"
        required: false
        fields:
          - name: "multipleChoiceQuestionImageSrc"
            label: "Image source"
            widget: "image"
            required: false
          - name: "multipleChoiceQuestionImageCaption"
            label: "Caption"
            widget: "string"
            required: false
      - label: "Options"
        name: "options"
        widget: "list"
        required: false
        fields:
          - label: "Text"
            name: "optionText"
            widget: "string"
            required: false
          - label: "Latitude"
            name: "latitude"
            widget: "string"
            required: false
            hint: "e.g. -12.460443"
          - label: "Longitude"
            name: "longitude"
            widget: "string"
            required: false
            hint: "e.g. 133.844517659562"
          - label: "Correct"
            name: "optionCorrect"
            widget: "boolean"
            required: false
  - name: matchingQuestions
    label: "Matching Question"
    editor:
      preview: false
    folder: content/matchingQuestions
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Question Text"
        name: "title"
        widget: "string"
        required: false
      - widget: "select"
        label: "Question type"
        name: "questionType"
        options: ["Drag and Drop"]
      - label: "Set 1 Title"
        name: "set1title"
        widget: "string"
        required: false
        hint: "e.g. Animals"
      - label: "Set 2 Title"
        name: "set2title"
        widget: "string"
        required: false
        hint: "e.g. Seasons"
      - label: "Set 1"
        name: "set1"
        widget: "list"
        required: false
        summary: "{{fields.set1item}}"
        fields:
          - label: "Set 1 item"
            name: "set1item"
            widget: "relation"
            collection: "quizItems"
            searchFields: ["title", "labelBininj"]
            valueField: "{{slug}}"
            displayFields: ["title", "labelBininj"]
          - label: "Item label"
            name: "title"
            widget: "string"
            required: false
            hint: "This is the label that will be displayed on the item in the quiz"
      - label: "Set 2"
        name: "set2"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - label: "Set 2 item"
            name: "set2item"
            widget: "relation"
            collection: "quizItems"
            searchFields: ["title", "labelBininj"]
            valueField: "{{slug}}"
            displayFields: ["title", "labelBininj"]
          - label: "Item label"
            name: "title"
            widget: "string"
            required: false
            hint: "This is the label that will be displayed on the item in the quiz"
      - label: "Matches"
        name: "matches"
        widget: "list"
        required: false
        summary: "{{fields.title}}"
        fields:
          - label: "Item 1"
            name: "match1"
            widget: "relation"
            collection: "quizItems"
            searchFields: ["title", "labelBininj"]
            valueField: "{{slug}}"
            displayFields: ["title", "labelBininj"]
            required: true
          - label: "Item 2"
            name: "match2"
            widget: "relation"
            collection: "quizItems"
            searchFields: ["title", "labelBininj"]
            valueField: "{{slug}}"
            displayFields: ["title", "labelBininj"]
            required: true
  - name: "quiz"
    label: "Quiz"
    delete: true
    editor:
      preview: false
    folder: content/quiz
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - label: "Title"
        name: "title"
        widget: "string"
        required: false
      - label: "Description"
        name: "description"
        widget: "text"
        required: false
      - widget: "object"
        label: "Image"
        name: "quizImage"
        required: true
        fields:
          - name: "quizImageSrc"
            label: "Image source"
            widget: "image"
            required: false
          - name: "quizImageCaption"
            label: "Caption"
            widget: "string"
            required: false
      - label: "Multiple Choice Questions"
        name: "multipleChoiceQuestions"
        widget: "list"
        required: false
        fields:
          - label: "Multiple Choice Question"
            name: "multipleChoiceQuestion"
            widget: "relation"
            collection: "multipleChoiceQuestions"
            searchFields: ["title"]
            valueField: "{{slug}}"
            displayFields: ["title"]
      - label: "Matching Questions"
        name: "matchingQuestions"
        widget: "list"
        required: false
        fields:
          - label: "Matching Question"
            name: "matchingQuestion"
            widget: "relation"
            collection: "matchingQuestions"
            searchFields: ["title"]
            valueField: "{{slug}}"
            displayFields: ["title"]
